#!/usr/bin/env python3
"""Mine the Radiant talent trees from the Stormlight core rulebook into a
dataset for the Cosmere builder (the orders/surges aren't in the Foundry
starter packs).

The rulebook is a two-column PDF, so pypdf's text interleaves columns and
produces some truncations/duplicates. We anchor on the regular talent format
(``Name`` / ``Prerequisite: X`` / effect), dedup by name within each tree, and
normalize the prerequisite into the tree-chain the builder needs:
  - "Speak the First Ideal"  -> {'ideal': 1}      (entry talents)
  - "<Name> talent"          -> {'talent': '<Name>'}
  - else                     -> {'text': '<raw>'}

Output: prints a Python module (systems/cosmere/radiant_talents.py) to stdout.
Dev tool — not run in CI; the generated module is committed.
Usage: python3 tools/extract_radiant_talents.py > systems/cosmere/radiant_talents.py
"""
from __future__ import annotations

import os
import re

import pypdf

PDF = os.path.expanduser('~/Downloads/Stormlight Rules_compressed.pdf')

SURGES = ['Abrasion', 'Adhesion', 'Cohesion', 'Division', 'Gravitation',
          'Illumination', 'Progression', 'Tension', 'Transformation', 'Transportation']
SURGE_CODE = {'Abrasion': 'abr', 'Adhesion': 'adh', 'Cohesion': 'chs', 'Division': 'dvs',
              'Gravitation': 'grv', 'Illumination': 'ill', 'Progression': 'prg',
              'Tension': 'tsn', 'Transformation': 'trs', 'Transportation': 'trp'}
ORDERS = ['Windrunner', 'Skybreaker', 'Dustbringer', 'Edgedancer', 'Truthwatcher',
          'Lightweaver', 'Elsecaller', 'Willshaper', 'Stoneward']
ORDER_KEY = {'Windrunner': 'windrunners', 'Skybreaker': 'skybreakers', 'Dustbringer': 'dustbringers',
             'Edgedancer': 'edgedancers', 'Truthwatcher': 'truthwatchers', 'Lightweaver': 'lightweavers',
             'Elsecaller': 'elsecallers', 'Willshaper': 'willshapers', 'Stoneward': 'stonewards'}


def _lines(reader, lo, hi):
    out = []
    for i in range(lo, hi):
        t = re.sub(r'[ \t]+', ' ', reader.pages[i].extract_text() or '')
        for l in t.split('\n'):
            l = l.strip()
            if l:
                out.append(l)
    return out


def _norm_prereq(raw):
    raw = raw.strip().rstrip('.')
    if 'First Ideal' in raw or raw.lower().startswith('speak the'):
        return {'ideal': 1}
    m = re.match(r'^(.*?)\s+talent$', raw)
    if m:
        return {'talent': m.group(1).strip()}
    return {'text': raw}


def _talents(lines, section_headers):
    """Parse talent blocks, tagging each with the current section header."""
    hdr_at = {}
    for i, l in enumerate(lines):
        for h, key in section_headers.items():
            if l == h:
                hdr_at[i] = key
    pidx = [i for i, l in enumerate(lines) if l.startswith('Prerequisite:')]

    def section_for(i):
        cur = None
        for k in sorted(hdr_at):
            if k < i:
                cur = hdr_at[k]
            else:
                break
        return cur

    out = {}
    seen = set()
    for n, pi in enumerate(pidx):
        name = lines[pi - 1].strip()
        if not (3 < len(name) < 46) or 'Chapter' in name or name.endswith(':'):
            continue
        if name[0] in '(),•◆▷' or re.match(r'^Level \d', name) or re.match(r'^\d', name):
            continue                                       # column-break fragments
        sec = section_for(pi)
        if not sec:
            continue
        if (sec, name.lower()) in seen:
            continue
        seen.add((sec, name.lower()))
        prereq = lines[pi][len('Prerequisite:'):].strip()
        end = (pidx[n + 1] - 1) if n + 1 < len(pidx) else len(lines)
        eff = re.sub(r'^Activation:?\s*', '', ' '.join(lines[pi + 1:end])).strip()
        eff = re.split(r'(?<=[.!])\s', eff)[0][:160]      # first sentence, capped
        out.setdefault(sec, []).append({'name': name, 'prereq': _norm_prereq(prereq), 'effect': eff})
    # Drop suffix-fragment duplicates ('Reclamation' when 'Stormlight Reclamation' exists).
    for sec, lst in out.items():
        names = [t['name'] for t in lst]
        out[sec] = [t for t in lst
                    if not any(o != t['name'] and o.endswith(' ' + t['name']) for o in names)]
    return out


def main():
    r = pypdf.PdfReader(PDF)
    surges = _talents(_lines(r, 214, 245), {s + ' Talents': SURGE_CODE[s] for s in SURGES})
    orders = _talents(_lines(r, 135, 212), {o: ORDER_KEY[o] for o in ORDERS})

    print('"""Radiant talent trees mined from the Stormlight core rulebook')
    print('(Ch.5 spren-bond trees + Ch.6 surge trees). GENERATED by')
    print('tools/extract_radiant_talents.py — the orders/surges are not in the')
    print('Foundry starter packs. Each talent: name, prereq ({ideal:1} = an entry')
    print('talent available once the First Ideal is sworn; {talent:X} = requires')
    print('talent X; {text:...} = other), and a short effect summary."""')
    print('from __future__ import annotations\n')
    print('# surge code -> [talent]')
    print('SURGE_TALENTS = {')
    for code in sorted(surges):
        print('    %r: [' % code)
        for t in surges[code]:
            print('        %r,' % t)
        print('    ],')
    print('}\n')
    print('# order key -> spren-bond [talent]')
    print('ORDER_TALENTS = {')
    for key in sorted(orders):
        print('    %r: [' % key)
        for t in orders[key]:
            print('        %r,' % t)
        print('    ],')
    print('}')


if __name__ == '__main__':
    main()
